### ISSUE TITLE
You do not have to initialize WaterDrop anymore ;)

### ISSUE THREAD

**Issue by mensfeld** [DoubleJarvis/async-arch-course#3]
Looking at the code:

https://github.com/DoubleJarvis/async-arch-course/blob/4c7e9d3a06b1f03c3dde33edbaf6fab56e037d77/popug_tasks/config/initializers/waterdrop.rb#L3

you can just now use

```ruby
Karafka.producer.produce_*
```

:)

**Comment by DoubleJarvis** [comment]
I didn't know that, thanks!
This is a learning project so I'll leave it as it is for now. I'll keep that in mind for future use. 
Just so you know, README.md from karafka/waterdrop doesn't seem to mention `Karafka.producer.produce_*` anywhere. It [does mention old way though ](https://github.com/karafka/waterdrop#using-waterdrop-across-the-application-and-with-ruby-on-rails)

**Comment by mensfeld** [comment]
@DoubleJarvis because it's WaterDrop readme not Karafka. The readme mentions this way because WaterDrop can be used as a standalone component.

Please use those docs for Karafka: https://karafka.io/docs/Producing-messages/
